config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # devise_for :installs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
    
  
  post 'set_seller', to: 'sellers#set_seller'
  get 'seller_product', to: 'sellers#seller_product'

  get 'cart_product', to: 'carts#cart_product'
  get 'carts', to: 'carts#user_carts'
  post 'remove_product', to: 'carts#remove_cart_product'
  
  get 'search',to:'products#search'
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success

  resources :registrations, only: [:new, :create,:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:edit,:update]
  resources :billing, only: [:index]

  resources :categories do
    member do
      get :product_by_category
    end
    resources :products
  end

  resources :carts do
    resources :products
  end

  resources :registrations do
    member do
      get :confirm_email
      patch :update_token
      get :show_user
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :cart_products
  	has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories


end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick 

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  belongs_to :user

  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :image

   validates :name,:description,:price,:quantity,  presence: true
  
  def search_data
    # {
    #   name: name,
    #   description: description
    # }

   { query: {
     multi_match: {
       fuzziness: 'AUTO',
       fields: %w[name description]
     }
   }}
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

	attr_accessor :skip_confirmation_token, :skip_role_define
	before_create {confirmation_token unless skip_confirmation_token}
  after_save {role_define unless skip_role_define}
	
  has_secure_password

	has_many :products ,dependent: :destroy
	has_and_belongs_to_many :roles
	has_one :cart  
  
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
	validates :password,
	:confirmation => true,
	:allow_blank => true,
	:on => :update
    
  
  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.skip_role_define = true
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.email_confirmed = true
        user.skip_confirmation_token = true
      end
    end
    user
  end

 # def self.email_activate user
 #    user.email_confirmed = true
 #    user.confirm_token = nil
 #    user.save!(:validate => false)
 #    #debugger
 # end

  def email_activate
  	self.email_confirmed = true
  	self.confirm_token = nil
  	self.save!(:validate => false)
  end

  
  private

	def confirmation_token
		if self.confirm_token.blank?
			self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end

	def role_define
    self.roles.create(name:"Buyer")
  end
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  protect_from_forgery except: :new_card
  
  def index
  end

	def new_card
    # respond_to do |format|
    #   format.js
    # end
  end

  def create_card
    respond_to do |format|
      if Current.user.stripe_id.nil?
        debugger
        customer = Stripe::Customer.create({"email": Current.user.email})
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email. 
        Current.user.update(:stripe_id => Current.user.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end

      card_token = params[:stripeToken]
      #it's the stripeToken that we added in the hidden input
      if card_token.nil?
        format.html { redirect_to billing_path, error: "Oops"}
      end
      #checking if a card was giving.

      customer = Stripe::Customer.new Current.user.stripe_id
      customer.source = card_token
      #we're attaching the card to the stripe customer
      customer.save

      format.html { redirect_to success_path }
    end
  end

  def success
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/billing/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-md-12 mt-5 text-center">
      Are you ready to pay? <%= Current.user.name%>
    </h1>
  </div>
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
     <%= form_tag create_payment_method_path, id: "billing-create-payment-method", remote: true do  %>
        <%= link_to "Let's go", add_payment_method_path, class: "btn btn-primary" %>
     <% end %>
    </div>
  </div>
</div>

app/views/billing/new_card.html.erb
<%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
<script>
    
    var handler = StripeCheckout.configure({
        key: '<%= Rails.application.credentials.stripe[Rails.env.to_sym][:publishable_key] %>',
        //get a publishable key that we put in editor depending on environment: production or development
        locale: 'auto',
        //handle translation
        name: "upload.express",
        description: "Add your credit card information",
        email: "<%= Current.user.email %>",
        panelLabel: "Add payment method",
        allowRememberMe: false,
        token: function (token) {
            
            var form = document.getElementById('billing-create-payment-method');
            
            //we will create element with this id in the next step
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card 
            form.appendChild(hiddenInput);
            //adding this input when we use a form.
            form.submit();
        }
    });

    handler.open();

    window.addEventListener('popstate', function() {
        handler.close();
    });

</script>

app/views/billing/new_card.js.erb
<%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
var handler = StripeCheckout.configure({
    key: '<%= Rails.application.credentials.stripe[Rails.env.to_sym][:publishable_key] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= Current.user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        
        var form = document.getElementById('billing-create-payment-method');
        
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card 
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/billing/success.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h2>You successfully linked a credit card to your account</h2>
    </div>
  </div>
</div>