config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # devise_for :installs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
    
  
  post 'set_seller', to: 'sellers#set_seller'
  get 'seller_product', to: 'sellers#seller_product'

  get 'cart_product', to: 'carts#cart_product'
  get 'carts', to: 'carts#user_carts'
  post 'remove_product', to: 'carts#remove_cart_product'
  
  get 'search',to:'products#search'
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success

  resources :registrations, only: [:new, :create,:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:edit,:update]
  resources :billing, only: [:index]

  resources :categories do
    member do
      get :product_by_category
    end
    resources :products
  end

  resources :carts do
    resources :products
  end

  resources :registrations do
    member do
      get :confirm_email
      patch :update_token
      get :show_user
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :cart_products
  	has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories


end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick 

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  belongs_to :user

  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :image

   validates :name,:description,:price,:quantity,  presence: true
  
  def search_data
    # {
    #   name: name,
    #   description: description
    # }

   { query: {
     multi_match: {
       fuzziness: 'AUTO',
       fields: %w[name description]
     }
   }}
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

	attr_accessor :skip_confirmation_token, :skip_role_define
	before_create {confirmation_token unless skip_confirmation_token}
  after_save {role_define unless skip_role_define}
	
  has_secure_password

	has_many :products ,dependent: :destroy
	has_and_belongs_to_many :roles
	has_one :cart  
  
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
	validates :password,
	:confirmation => true,
	:allow_blank => true,
	:on => :update
    
  
  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.skip_role_define = true
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.email_confirmed = true
        user.skip_confirmation_token = true
      end
    end
    user
  end

 # def self.email_activate user
 #    user.email_confirmed = true
 #    user.confirm_token = nil
 #    user.save!(:validate => false)
 #    #debugger
 # end

  def email_activate
  	self.email_confirmed = true
  	self.confirm_token = nil
  	self.save!(:validate => false)
  end

  
  private

	def confirmation_token
		if self.confirm_token.blank?
			self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end

	def role_define
    self.roles.create(name:"Buyer")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_user_logged_in!

  
  def user_carts
    @user = User.find(Current.user.id)
    @cart = @user.cart
    #debugger
    if @cart.nil?
      redirect_to root_path, alert:"you don't have any product in cart"
    else
      @cartproducts = @cart.products
    end
  end


  def create
    @user = User.find(Current.user.id)#debugger
    if Cart.find_by(user_id: @user.id)
      # debugger
      cart_product
    else
      @cart = @user.build_cart(cart_params)
      if @cart.save
        #debugger
        cart_product
      else
        redirect_to root_path, alert:'cart is not created'
      end
    end
  end

  def destroy
  end

  
  def cart_product
    @user = User.find(Current.user.id)
    @cart = Cart.find_by(user_id: @user.id)
   cart_prod = CartProduct.find_by(cart_id: @cart.id,product_id: params[:product_id])
   if cart_prod.nil?
      cart_prod = CartProduct.new(cart_id: @cart.id,product_id: params[:product_id])
      if cart_prod.save
        redirect_to carts_path, notice:'added to the cart'
      else
        redirect_to carts_path, alert:'something is wrong'
      end
    else
      redirect_to carts_path, notice:'already added to the cart'
    end
  end

  def remove_cart_product
    # debugger
    @cart_product = CartProduct.find_by(cart_id: params[:cart_id], product_id: params[:product_id])
    if @cart_product.destroy
      redirect_to carts_path, notice:'product removed successfully'
    end
  end



  private

  def cart_params
    params.permit(:product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/carts/user_carts.html.erb
  <% @cartproducts.each do |f| %>
  <%if f.image.blank?%>
  <p>image not uploaded</p>
  <%else%>
  <%= image_tag f.image %>
  <%end%>
  <%if f.quantity.blank?%>
  <p>Out of stock</p>
  <%else%>
   
  <div> 
    <div class="quantity"> <input name="quantity"  id="quantity_<%= f.id %>"  value="<%= f.quantity%>" style="border: 0px" readonly>
    </div>
    <%end%> 

    <div>ProductName: <input name="ProductName" id="name_<%= f.id %>" type="text" value="<%= f.name%>" style="border: 0px" readonly>
    </div>
  
    <div class='price'>Price: <span><input name="price"  id='price_<%= f.id %>' type="text" value=<%= f.price.to_i %> readonly/></span></div><br>
  
    <div class='qty'> Qty: <input name="qty" class="pro-qty" type="text" id='qty_<%= f.id %>' value="1" />  
    </div><br>

    <div>
    Total:
    <input name="total" class="prod-total" id="total_<%= f.id %>" type="text" value=<%= f.price.to_i %> readonly/>
    <%= button_to 'remove',remove_product_path(product_id: f.id, cart_id: @cart.id)%>  
    </div><br>

    <script>
      $( document ).ready( function() { 
        sum = 0;
        $("input[class *= 'prod-total']").each(function(){
        sum += +$(this).val();
        });
        $(".total").val(sum);

        $(".pro-qty").keyup(function(){

          var product_id = this.id.split("_")[1]
          var avail_qty = $("#quantity_"+product_id).val(); 
          var qty = $("#qty_"+product_id).val();  
          var price = $("#price_"+product_id).val();
          var total=isNaN(parseInt(qty*price)) ? 0 :(qty* price)
          $("#total_"+product_id).val(total);
          avail_qty = parseInt(avail_qty)
          qty = parseInt(qty)
          if (avail_qty <= qty){
            alert("product can be buy upto "+avail_qty);
            $("#qty_"+product_id).val(0);
            $("#total_"+product_id).val(0);
          }
  
        sum = 0;
        $("input[class *= 'prod-total']").each(function(){
          sum += +$(this).val();
        });
        
        $(".total").val(sum);
      });});
    </script>
  </div>

<%end%>
<% if @cartproducts.blank?%>
<center><h1>there is no product in cart<h1></center>
<%else%>
<div class="total">Total_price:<input name='total-price' class="total" type="text" readonly></div>
<%= link_to 'PAYMENT',billing_index_path %>
<%end%>