config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # devise_for :installs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
    
  
  post 'set_seller', to: 'sellers#set_seller'
  get 'seller_product', to: 'sellers#seller_product'

  get 'cart_product', to: 'carts#cart_product'
  get 'carts', to: 'carts#user_carts'
  post 'remove_product', to: 'carts#remove_cart_product'
  
  get 'search',to:'products#search'
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success

  resources :registrations, only: [:new, :create,:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:edit,:update]
  resources :billing, only: [:index]

  resources :categories do
    member do
      get :product_by_category
    end
    resources :products
  end

  resources :carts do
    resources :products
  end

  resources :registrations do
    member do
      get :confirm_email
      patch :update_token
      get :show_user
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :cart_products
  	has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories


end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick 

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  belongs_to :user

  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :image

   validates :name,:description,:price,:quantity,  presence: true
  
  def search_data
    # {
    #   name: name,
    #   description: description
    # }

   { query: {
     multi_match: {
       fuzziness: 'AUTO',
       fields: %w[name description]
     }
   }}
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

	attr_accessor :skip_confirmation_token, :skip_role_define
	before_create {confirmation_token unless skip_confirmation_token}
  after_save {role_define unless skip_role_define}
	
  has_secure_password

	has_many :products ,dependent: :destroy
	has_and_belongs_to_many :roles
	has_one :cart  
  
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
	validates :password,
	:confirmation => true,
	:allow_blank => true,
	:on => :update
    
  
  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.skip_role_define = true
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.email_confirmed = true
        user.skip_confirmation_token = true
      end
    end
    user
  end

 # def self.email_activate user
 #    user.email_confirmed = true
 #    user.confirm_token = nil
 #    user.save!(:validate => false)
 #    #debugger
 # end

  def email_activate
  	self.email_confirmed = true
  	self.confirm_token = nil
  	self.save!(:validate => false)
  end

  
  private

	def confirmation_token
		if self.confirm_token.blank?
			self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end

	def role_define
    self.roles.create(name:"Buyer")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_user_logged_in!

  
  def user_carts
    @user = User.find(Current.user.id)
    @cart = @user.cart
    #debugger
    if @cart.nil?
      redirect_to root_path, alert:"you don't have any product in cart"
    else
      @cartproducts = @cart.products
    end
  end


  def create
    @user = User.find(Current.user.id)#debugger
    if Cart.find_by(user_id: @user.id)
      # debugger
      cart_product
    else
      @cart = @user.build_cart(cart_params)
      if @cart.save
        #debugger
        cart_product
      else
        redirect_to root_path, alert:'cart is not created'
      end
    end
  end

  def destroy
  end

  
  def cart_product
    @user = User.find(Current.user.id)
    @cart = Cart.find_by(user_id: @user.id)
   cart_prod = CartProduct.find_by(cart_id: @cart.id,product_id: params[:product_id])
   if cart_prod.nil?
      cart_prod = CartProduct.new(cart_id: @cart.id,product_id: params[:product_id])
      if cart_prod.save
        redirect_to carts_path, notice:'added to the cart'
      else
        redirect_to carts_path, alert:'something is wrong'
      end
    else
      redirect_to carts_path, notice:'already added to the cart'
    end
  end

  def remove_cart_product
    # debugger
    @cart_product = CartProduct.find_by(cart_id: params[:cart_id], product_id: params[:product_id])
    if @cart_product.destroy
      redirect_to carts_path, notice:'product removed successfully'
    end
  end



  private

  def cart_params
    params.permit(:product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
  def index
    @categories = Category.all
		@products = Product.all
	end

  def search
    if params[:search].blank?
      redirect_to root_path, alert:'there is no product you want'
    else
      @prod = params[:search]
      @products = Product.search("%#{@prod}%", page: params[:page], per_page: 20)
      if @products.blank?
        redirect_to root_path, alert:'there is no product you want'
      end
    end
  end

  def new
    #debugger
    @category = Category.find(params[:category_id])
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end


  def create
    #debugger
    @category = Category.find(params[:category_id])
    @product = @category.products.new(product_params)
    @category.products << @product
    if @product.save
      #@product.reindex
      redirect_to seller_product_path, notice:'product added successfully'
    else
      
      redirect_to new_category_product_path, alert:"field can't be empty"
    end
  end

  def edit
    #debugger
    @category = Category.find(params[:category_id])
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to seller_product_path, notice:'product has been updated'
    else
      redirect_to seller_product_path, alert:"something is wrong"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to seller_product_path, notice:'product has been deleted'
    else
      redirect_to seller_product_path, alert:'something is wrong'
    end
  end


  private
  def product_params
    params.require(:product).permit(:name,:description,:price,:user_id,:category_id,:image,:search,:quantity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/products/edit.html.erb
<center>
  <h2> Update product </h2>
  <%= form_with url: category_product_path(@category.id,user_id:Current.user.id),method: :patch do |f| %>
  <p>
    <%= f.label 'name:'%><br>
    <input name="name"  id="name"  value="<%= @product.name%>" >
    <%#= f.text_field :name, id: 'name' %>
  </p>

  <p>
    <%unless @product.image.blank?%>
    <%= image_tag @product.image%><br>
    <%end%>
    <%= f.file_field :image, id: 'image' %>
  </p>

    
  <p>
    <%= f.label 'description:'%><br>
    <input name="description"  id="description"  value="<%= @product.description%>" >
    <%#= f.text_field :description, id: 'description' %>
  </p>
    
  <p>
    <%= f.label 'price:'%><br>
    <input name="price"  id="price"  value="<%= @product.price%>" >
    <%#= f.text_field :price, id: 'price' %>
  </p>

  <p>
    <%= f.label 'quantity:'%><br>
    <input name="quantity"  id="quantity"  value="<%= @product.quantity%>" >
    <%#= f.text_field :quantity, id: 'quantity' %>
  </p>
  <%= f.submit 'Update Product' %>
  <%end%></center>

app/views/products/index.html.erb
  <% @categories.each do |f|%>
  <%=link_to "#{f.name}", product_by_category_category_path(f.id)%>
  <%end%>

<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://img.freepik.com/free-vector/household-appliances-realistic-composition_1284-65307.jpg?t=st=1652340225~exp=1652340825~hmac=13dc890807bb98829f1a66e404c8e877c594c9f5ac3df35c9bd56c85ef996fde&w=740" style="width: 25px;height: 370px;" class="d-block w-100" alt="...">
    </div>

    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://img.freepik.com/free-photo/brown-sofa-wooden-table-living-room-interior-with-plant-concrete-wall_41470-3721.jpg?t=st=1652344510~exp=1652345110~hmac=6da7ea0b60976c3d65250594a95df2203a37a42f9a5da55ef8d5955d366b199b&w=740" style="width: 25px;height: 370px;" class="d-block w-100" alt="...">
    </div>
    
    <div class="carousel-item">
      <img src="https://img.freepik.com/free-vector/set-different-home-appliances-kit-electric-house-equipment-collection-flat-horizontal-copy-space_48369-26076.jpg?w=826" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<%= render partial: "shared/product", locals: {product: @products}  %>

app/views/products/new.html.erb
<center>
  <h2> Add product </h2>
  <%= form_with model: @product, url: category_products_path(@category.id) do |f| %>
  <p>
    <%= f.label 'name:'%><br>
    <%= f.text_field :name, id: 'name' %>
  </p>

  <p>
    <%= f.file_field :image, id: 'image' %>
  </p>

    
  <p>
    <%= f.label 'description:'%><br>
    <%= f.text_field :description, id: 'description' %>
  </p>
    
  <p>
    <%= f.label 'price:'%><br>
    <%= f.text_field :price, id: 'price' %>
  </p>

  <p>
    <%= f.label 'quantity:'%><br>
    <%= f.text_field :quantity, id: 'quantity' %>
  </p>
   
  <%= f.hidden_field :user_id , value: Current.user.id%> 
  <%= f.hidden_field :category_id , value: @category.id%> 

  <%= f.submit 'Create Product' %>
  <%end%></center>

app/views/products/search.html.erb
<%= render partial: "shared/product", locals: {product: @products}  %>

app/views/products/show.html.erb
<%= link_to 'Back', root_path %>

<h1><%= @product.name.capitalize %></h1>

<div class="card" style="width: 18rem;">
  <%if @product.image.present?%>
    <%= image_tag @product.image%>
  <%else%>
    <img class="card-img-top" src="..." alt="Card image cap"> 
  <%end%>

  <div class="card-body">
    <h5 class="card-title"><%= @product.name%></h5>
    <p class="card-text"><%= @product.description%></p>
    <p class="card-text"><%= @product.price%></p>
  </div>
</div>

<% if Current.user.nil?%>
  <%= link_to "Add to cart", new_session_path, class: "btn btn-primary"%>
<% else %>
  <% if Current.user.id == @product.user_id%>
<%else%>
  <%= button_to "Add to cart", carts_path(product_id: @product.id), method: :POST %>
<% end %>
<% end %>