config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  # devise_for :installs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
    
  
  post 'set_seller', to: 'sellers#set_seller'
  get 'seller_product', to: 'sellers#seller_product'

  get 'cart_product', to: 'carts#cart_product'
  get 'carts', to: 'carts#user_carts'
  post 'remove_product', to: 'carts#remove_cart_product'
  
  get 'search',to:'products#search'
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  post "/card" => "billing#create_card", as: :create_payment_method
  get '/success' => 'billing#success', as: :success

  resources :registrations, only: [:new, :create,:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:edit,:update]
  resources :billing, only: [:index]

  resources :categories do
    member do
      get :product_by_category
    end
    resources :products
  end

  resources :carts do
    resources :products
  end

  resources :registrations do
    member do
      get :confirm_email
      patch :update_token
      get :show_user
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	has_many :cart_products
  	has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories


end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick 

  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
  belongs_to :user

  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :image

   validates :name,:description,:price,:quantity,  presence: true
  
  def search_data
    # {
    #   name: name,
    #   description: description
    # }

   { query: {
     multi_match: {
       fuzziness: 'AUTO',
       fields: %w[name description]
     }
   }}
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :product
	belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

	attr_accessor :skip_confirmation_token, :skip_role_define
	before_create {confirmation_token unless skip_confirmation_token}
  after_save {role_define unless skip_role_define}
	
  has_secure_password

	has_many :products ,dependent: :destroy
	has_and_belongs_to_many :roles
	has_one :cart  
  
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
	validates :password,
	:confirmation => true,
	:allow_blank => true,
	:on => :update
    
  
  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.skip_role_define = true
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.email_confirmed = true
        user.skip_confirmation_token = true
      end
    end
    user
  end

 # def self.email_activate user
 #    user.email_confirmed = true
 #    user.confirm_token = nil
 #    user.save!(:validate => false)
 #    #debugger
 # end

  def email_activate
  	self.email_confirmed = true
  	self.confirm_token = nil
  	self.save!(:validate => false)
  end

  
  private

	def confirmation_token
		if self.confirm_token.blank?
			self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end

	def role_define
    self.roles.create(name:"Buyer")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_header.html.erb
<style type="text/css">
  .search-form input{
    width: 100%;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 8px;
  }
  .search-form form{
    display: flex;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  &nbsp;&nbsp;&nbsp;&nbsp;
  <div class="container-fluid">
    <a class="navbar-brand">
    <%= link_to root_path do %>
      <img src="https://1000logos.net/wp-content/uploads/2021/02/Flipkart-logo.png" style="width: 70px;height: 38px;" >
      <%end%>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item search-form">
          <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
          <%=form_tag search_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search] %>
          <%= button_to "Search", :name => nil %>
          <% end %>

        </li>&nbsp;&nbsp;&nbsp;&nbsp;

        <%if !Current.user.nil?%> 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            	<li><%#= link_to 'Edit password', "#",class: "dropdown-item" %></li>
              <% @user = User.find(Current.user.id)%>
            	<li><a class="dropdown-item" href="<%= edit_password_path(@user.id) %>" >Edit password</a></li>
              <li><a class="dropdown-item" href="<%= carts_path%>">cart</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'Logout', session_path(@user.id), method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>

          <!-- <li class="nav-item">
            <a class="nav-link " href="#" tabindex="-1" >Login_as: <%#= Current.user.email %></a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link " href="<%= carts_path %>" tabindex="-1" >Cart</a>
          </li>
        <%else%>   
          <%= link_to 'Login', new_session_path %>
        <%end%>

         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <li class="nav-item">
      <%if !Current.user.nil?%>
      <%user = Current.user%>
      <%role = user.roles.collect(&:name)%>
       <% unless role.include?("Seller")%>         
      <%= button_to 'Become a seller', set_seller_path, method: :post, class: "btn btn-sm btn-primary" %></li>&nbsp;&nbsp;&nbsp;
      <%end%>
      <% if role.include?("Seller")%>         
      <%= link_to 'my_products', seller_product_path%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <li><%= button_to 'Add Products', categories_path, method: :get, class: "btn btn-sm btn-primary"%></li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%end%>
    <%end%>
      
      <%if !Current.user.nil?%>
      
      <li class="nav-item" style="margin-left: 487px;">
          <a class="nav-link " href="<%= show_user_registration_path(id: Current.user.id)%>" tabindex="-1" >Login_as: <%= Current.user.email %></a>
      </li>
      <%end%>
      
      
      </ul>
      <%#= link_to "Admin_user", "new_admin_user_path" ,class: "btn btn-sm btn-primary"%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoppingkart1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p><% end %>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_product.html.erb
   <div class="">
     <div class="row m-0">
      <% product.each do |f|%>
       <div class="card col-lg-3">
        <%if f.image.present?%>
          <%= cl_image_tag f.image.key %>
        <%else%>
        missing image
        <img class="card-img-top" src="..." alt="Card image cap"> 
        <%end%>
          <div class="card-body">
            <h5 class="card-title"><%= f.name %></h5>
            <p class="card-text">price:<%= f.price %>/-</p>
            <a href="View_product"><%= link_to "viewproduct",category_product_path(f.category_id,f.id)%></a>
          </div>
          </div>
          <%end%>
     </div>
   </div>